spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      topic: "new-video"
      group: "new-video"
      partition: ${PARTITION}
    producer:
      topic: "download-error"
      topic-info-video: "info-video"

  application:
    name: userbot
tdlib:
  id: ${TDLIB_ID}
  hash: ${TDLIB_HASH}
  pathDataBase: "tdlib/tdlib-db"
  pathDownload: "tdlib/tdlib-download"
  phoneNumber: ${TDLIB_PHONE_NUMBER}
logging:
  level:
    it.tdlight: ERROR
redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}
#  tls:
#    password: changeit
bot:
  chat_id: ${TG_CHATS}
  pool-task: ${POOL_TASK}
  cookies:
    cookies-path: /data/cookies.txt
